"""empty message

Revision ID: 16b9353589ed
Revises: dcefb10a837d
Create Date: 2023-05-14 21:29:09.649067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16b9353589ed'
down_revision = 'dcefb10a837d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloth', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
