"""empty message

Revision ID: 3f92fd70c4cb
Revises: 16b9353589ed
Create Date: 2023-05-16 14:19:28.352519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f92fd70c4cb'
down_revision = '16b9353589ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indoor_climate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    with op.batch_alter_table('outdoor_climate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outdoor_climate', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('indoor_climate', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
