"""empty message

Revision ID: 77e4a2c8a6ae
Revises: 
Create Date: 2023-05-13 15:41:42.816196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e4a2c8a6ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=False),
    sa.Column('temp_out', sa.Float(), nullable=False),
    sa.Column('humi_out', sa.Float(), nullable=False),
    sa.Column('pressure_out', sa.Float(), nullable=False),
    sa.Column('temp_in', sa.Float(), nullable=False),
    sa.Column('humi_in', sa.Float(), nullable=False),
    sa.Column('api_in', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('cloth',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloth_name', sa.String(length=100), nullable=False),
    sa.Column('coor', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('cloth')
    op.drop_table('climate')
    # ### end Alembic commands ###
