"""empty message

Revision ID: c664b8d600a6
Revises: 3f92fd70c4cb
Create Date: 2023-05-26 00:12:09.299115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c664b8d600a6'
down_revision = '3f92fd70c4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecast',
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day_weather', sa.String(length=50), nullable=True),
    sa.Column('night_weather', sa.String(length=50), nullable=True),
    sa.Column('day_temp', sa.Float(), nullable=True),
    sa.Column('night_temp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('outdoor_climate', schema=None) as batch_op:
        batch_op.alter_column('pressure_out',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outdoor_climate', schema=None) as batch_op:
        batch_op.alter_column('pressure_out',
               existing_type=sa.String(length=10),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    op.drop_table('weather_forecast')
    # ### end Alembic commands ###
