"""empty message

Revision ID: dcefb10a837d
Revises: 77e4a2c8a6ae
Create Date: 2023-05-14 16:10:30.799582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcefb10a837d'
down_revision = '77e4a2c8a6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indoor_climate',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('temp_in', sa.Float(), nullable=False),
    sa.Column('humi_in', sa.Float(), nullable=False),
    sa.Column('api_in', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('outdoor_climate',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=False),
    sa.Column('temp_out', sa.Float(), nullable=False),
    sa.Column('humi_out', sa.Float(), nullable=False),
    sa.Column('pressure_out', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    op.drop_table('climate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate',
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('weather', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('temp_out', mysql.FLOAT(), nullable=False),
    sa.Column('humi_out', mysql.FLOAT(), nullable=False),
    sa.Column('pressure_out', mysql.FLOAT(), nullable=False),
    sa.Column('temp_in', mysql.FLOAT(), nullable=False),
    sa.Column('humi_in', mysql.FLOAT(), nullable=False),
    sa.Column('api_in', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('outdoor_climate')
    op.drop_table('indoor_climate')
    # ### end Alembic commands ###
