"""empty message

Revision ID: eab8c8a0edcc
Revises: c664b8d600a6
Create Date: 2023-06-02 00:50:09.548954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab8c8a0edcc'
down_revision = 'c664b8d600a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloth', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
